# Multi-backend configuration examples for s3-bench

# Example 1: S3 backend with target base URI
target: "s3://my-bucket/test-data/"
duration: "60s"
concurrency: 16

workload:
  # GET from relative paths under s3://my-bucket/test-data/
  - op: get
    path: "input/*"          # Expands to s3://my-bucket/test-data/input/*
    weight: 70

  # PUT to relative paths under s3://my-bucket/test-data/
  - op: put
    path: "output/"          # Puts to s3://my-bucket/test-data/output/obj_123456
    object_size: 1048576     # 1 MiB
    weight: 30

---

# Example 2: Local file system backend
target: "file:///tmp/s3bench-test/"
duration: "30s"
concurrency: 8

workload:
  - op: get
    path: "data/*"           # Expands to file:///tmp/s3bench-test/data/*
    weight: 60

  - op: put
    path: "results/"         # Puts to file:///tmp/s3bench-test/results/obj_123456
    object_size: 65536       # 64 KiB
    weight: 40

---

# Example 3: Direct I/O backend
target: "direct:///mnt/nvme/benchmark/"
duration: "120s"
concurrency: 32

workload:
  - op: get
    path: "workload.bin"     # Direct access: direct:///mnt/nvme/benchmark/workload.bin
    weight: 80

  - op: put
    path: "output/"          # Writes to direct:///mnt/nvme/benchmark/output/obj_123456
    object_size: 4194304     # 4 MiB
    weight: 20

---

# Example 4: Azure Blob (future support)
target: "az://mystorageaccount/container/path/"
duration: "90s"
concurrency: 24

workload:
  - op: get
    path: "archive/*.dat"    # Expands to az://mystorageaccount/container/path/archive/*.dat
    weight: 50

  - op: put
    path: "staging/"         # Puts to az://mystorageaccount/container/path/staging/obj_123456
    object_size: 2097152     # 2 MiB
    weight: 50

---

# Example 5: Absolute URIs (no target specified)
duration: "45s"
concurrency: 12

workload:
  # Mix of different backends in same workload
  - op: get
    path: "s3://bucket1/data/*"
    weight: 40

  - op: get  
    path: "file:///local/cache/*"
    weight: 30

  - op: put
    path: "s3://bucket2/results/"
    object_size: 524288      # 512 KiB
    weight: 30